name: LaTeX Compilation and Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write    # For creating releases
  pages: write       # For deploying to Pages
  id-token: write    # Required for Pages deployment

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
     # Step 1: Compile LaTeX to PDF using LuaLaTeX
      - name: Compile LaTeX document to PDF
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          latexmk_use_lualatex: true
          latexmk_shell_escape: true
          extra_system_packages: "inkscape"
      
      # Step 2: Upload PDF as artifact
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: main.pdf
      
      # Step 3: Create a release with the PDF
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          name: Latest PDF Build
          files: main.pdf
          body: Automatically generated PDF from LaTeX source
          draft: false
          prerelease: false
      
      # Step 4: Convert LaTeX to HTML using make4ht
      - name: Convert LaTeX to HTML
        uses: docker://ghcr.io/michal-h21/make4ht-action:latest
        env:
          command: "make4ht -ulm draft -d html main.tex 'mathjax,svg'"
      
      # Step 5: Upload Pages artifact
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./html

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
